-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.todos
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.todos
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();

CREATE POLICY "Enable insert for authenticated users only"
    ON public.todos
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.role() = 'authenticated'::text));


CREATE POLICY "Enable delete for users based on user_id"
    ON public.todos
    AS PERMISSIVE
    FOR DELETE
    TO public
    USING ((requesting_user_id() = user_id));

CREATE POLICY "Enable access to own todos"
    ON public.todos
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((requesting_user_id() = user_id));
