-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.requesting_user_id(
	)
    RETURNS text
    LANGUAGE 'sql'
    COST 100
    STABLE PARALLEL UNSAFE
AS $BODY$
  select nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::text;
$BODY$;

ALTER FUNCTION public.requesting_user_id()
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.requesting_user_id() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.requesting_user_id() TO anon;

GRANT EXECUTE ON FUNCTION public.requesting_user_id() TO authenticated;

GRANT EXECUTE ON FUNCTION public.requesting_user_id() TO postgres;

GRANT EXECUTE ON FUNCTION public.requesting_user_id() TO service_role;

ALTER TABLE IF EXISTS public.users
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.users
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();

CREATE POLICY "Enable access to own user"
    ON public.users
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((requesting_user_id() = user_id));
