-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE POLICY "Authenticated users access to JPG images in folder avatars" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'avatars' AND storage."extension"(name) = 'jpeg' AND LOWER((storage.foldername(name))[1]) = 'public' AND auth.role() = 'authenticated');